spring.application.name=empManagement

#
#spring.datasource.url=jdbc:mysql://localhost:3306/kec
#spring.datasource.username=root
#spring.datasource.password=rdp1971
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.profiles.active=true